In [1]:
import investpy
import pandas as pd

In [2]:
#Obtener la tabla en tiempo real de la bolsa de españa
investpy.stocks.get_stocks_overview(country='spain', as_json = False , n_results = 35)

,country,name,symbol,last,high,low,change,change_percentage,turnover,currency
0,spain,ACS,ACS,23.400,23.4900,23.1050,+0.670,+2.95%,314070,EUR
1,spain,Atresmedia,A3M,3.572,3.5900,3.4520,+0.102,+2.94%,314980,EUR
2,spain,Acerinox,ACX,11.160,11.2050,10.9420,+0.220,+2.01%,656300,EUR
3,spain,BBVA,BBVA,5.410,5.4600,5.2900,+0.129,+2.44%,10670000,EUR
4,spain,Bankinter,BKT,4.948,4.9700,4.8890,+0.066,+1.35%,1080000,EUR
5,spain,Acciona,ANA,144.600,146.8000,143.4000,0.000,0.00%,59760,EUR
6,spain,Caixabank,CABK,2.576,2.5920,2.5250,+0.066,+2.63%,5680000,EUR
7,spain,Enagas,ENAG,19.240,19.3300,19.0750,+0.100,+0.52%,321030,EUR
8,spain,FCC,FCC,10.820,10.9500,10.7800,+0.120,+1.12%,34910,EUR
9,spain,Naturgy Energy,NTGY,21.550,21.5950,21.4050,+0.060,+0.28%,0,EUR
10,spain,Gamesa,SGREN,22.500,22.7000,22.2500,+0.230,+1.03%,412740,EUR
11,spain,Grifols,GRLS,22.044,22.4700,21.7500,-0.186,-0.84%,554340,EUR
12,spain,Ferrovial,FER,25.280,25.5750,25.1750,+0.090,+0.36%,348130,EUR
13,spain,Red Electrica,REE,17.540,17.8080,17.4480,-0.195,-1.10%,530920,EUR
14,spain,Inditex,ITX,32.195,32.6350,31.9450,-0.105,-0.33%,1240000,EUR
15,spain,Repsol,REP,10.470,10.6250,10.3600,+0.255,+2.50%,4099999,EUR
16,spain,Iberdrola,IBE,9.271,9.4050,9.2400,-0.063,-0.67%,5620000,EUR
17,spain,Indra A,IDR,9.295,9.3900,9.2870,+0.070,+0.76%,379110,EUR
18,spain,Mapfre,MAP,1.805,1.8100,1.7900,+0.031,+1.75%,1390000,EUR
19,spain,Telefonica,TEF,4.064,4.1200,4.0520,+0.012,+0.30%,7600000,EUR
20,spain,Mediaset,TL5,4.864,4.8680,4.7240,+0.178,+3.80%,249890,EUR
21,spain,Sacyr,SCYR,2.140,2.1580,2.0890,+0.038,+1.81%,1230000,EUR
22,spain,Banco de Sabadell,ACS,0.649,0.6550,0.6230,+0.033,+5.36%,42080000,EUR
23,spain,Santander,SAN,2.989,2.9950,2.9160,+0.089,+3.07%,20330000,EUR
24,spain,Inmobiliaria Colonial,COL,8.795,8.9530,8.7650,-0.065,-0.73%,278600,EUR
25,spain,Tecnicas Reunidas,TRE,7.740,7.7720,7.5770,+0.245,+3.27%,233790,EUR
26,spain,OHL,OHL,0.610,0.6150,0.5970,+0.020,+3.39%,1710000,EUR
27,spain,IAG,ICAG,2.025,2.0340,1.9900,+0.029,+1.45%,12460000,EUR
28,spain,Ebro Foods,EBRO,16.470,16.8290,16.4190,-0.140,-0.84%,103260,EUR
29,spain,Endesa,ELE,18.230,18.4120,18.1330,-0.145,-0.79%,570100,EUR
30,spain,Amadeus,AMA,56.020,56.9100,55.5390,-0.469,-0.83%,409950,EUR
31,spain,DIA,DIDA,0.014,0.0161,0.0138,-0.0018,-11.39%,393330000,EUR
32,spain,Vertice 360 Grados,VTSG,3.745,3.8000,3.7450,-0.0500,-1.32%,350,EUR
33,spain,Laborat.Rovi,ROVI,56.400,57.0000,56.0000,-0.100,-0.18%,48090,EUR
34,spain,General Alquiler Maquinaria,GALQ,1.540,1.5400,1.5350,+0.030,+1.99%,2650,EUR